/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CarritoRouteImport } from './routes/carrito'
import { Route as CatalogoRouteImport } from './routes/catalogo'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as EnviosRouteImport } from './routes/envios'
import { Route as FavoritosRouteImport } from './routes/favoritos'
import { Route as PersonalizarRamoRouteImport } from './routes/personalizar-ramo'
import { Route as RosasEternasRouteImport } from './routes/rosas-eternas'
import { Route as ServiciosRouteImport } from './routes/servicios'
import { Route as SobreNosotrosRouteImport } from './routes/sobre-nosotros'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedMiCuentaRouteImport } from './routes/_authenticated/mi-cuenta'
import { Route as ApiAuditLogsRouteImport } from './routes/api.audit-logs'
import { Route as ApiConfirmationRouteImport } from './routes/api.confirmation'
import { Route as ApiOrdersRouteImport } from './routes/api.orders'
import { Route as ApiProductImagesRouteImport } from './routes/api.product-images'
import { Route as ApiProductsRouteImport } from './routes/api.products'
import { Route as ApiWebhookEventsRouteImport } from './routes/api.webhook-events'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthResetPasswordRouteImport } from './routes/auth.reset-password'
import { Route as AuthResetPasswordConfirmRouteImport } from './routes/auth.reset-password-confirm'
import { Route as ConfirmationOrderIdRouteImport } from './routes/confirmation.$orderId'
import { Route as DebugGhlTestRouteImport } from './routes/debug.ghl-test'
import { Route as LegalSlugRouteImport } from './routes/legal.$slug'
import { Route as ProductoIdRouteImport } from './routes/producto.$id'
import { Route as ServiciosIndexRouteImport } from './routes/servicios.index'
import { Route as ServiciosSlugRouteImport } from './routes/servicios.$slug'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminDashboardRouteImport } from './routes/_authenticated/admin/dashboard'
import { Route as AuthenticatedAdminOrdersRouteImport } from './routes/_authenticated/admin/orders'
import { Route as AuthenticatedAdminProductsRouteImport } from './routes/_authenticated/admin/products'
import { Route as AuthenticatedAdminReportsRouteImport } from './routes/_authenticated/admin/reports'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin/settings'
import { Route as AuthenticatedAdminWebhooksRouteImport } from './routes/_authenticated/admin/webhooks'
import { Route as ApiAdminDebugEnvRouteImport } from './routes/api.admin.debug-env'
import { Route as ApiAdminDebugMetadataRouteImport } from './routes/api.admin.debug-metadata'
import { Route as ApiAdminDiagnoseMetadataRouteImport } from './routes/api.admin.diagnose-metadata'
import { Route as ApiAdminPopulateMetadataRouteImport } from './routes/api.admin.populate-metadata'
import { Route as ApiAdminProductsRouteImport } from './routes/api.admin.products'
import { Route as ApiAdminSyncCatalogRouteImport } from './routes/api.admin.sync-catalog'
import { Route as ApiDashboardStatsRouteImport } from './routes/api.dashboard.stats'
import { Route as ApiGhlProductsRouteImport } from './routes/api.ghl.products'
import { Route as ApiOrdersIdRouteImport } from './routes/api.orders.$id'
import { Route as ApiProductsIdRouteImport } from './routes/api.products.$id'
import { Route as ApiUploadProductImageRouteImport } from './routes/api.upload.product-image'
import { Route as ApiWebhooksGhlOpportunityRouteImport } from './routes/api.webhooks.ghl-opportunity'
import { Route as ApiWebhooksGhlProductRouteImport } from './routes/api.webhooks.ghl-product'
import { Route as AuthenticatedAdminOrdersIndexRouteImport } from './routes/_authenticated/admin/orders.index'
import { Route as AuthenticatedAdminOrdersIdRouteImport } from './routes/_authenticated/admin/orders.$id'
import { Route as AuthenticatedAdminProductsIndexRouteImport } from './routes/_authenticated/admin/products.index'
import { Route as AuthenticatedAdminProductsIdRouteImport } from './routes/_authenticated/admin/products.$id'
import { Route as AuthenticatedAdminProductsNewRouteImport } from './routes/_authenticated/admin/products.new'
import { Route as ApiAdminProductsIdRouteImport } from './routes/api.admin.products.$id'
import { Route as ApiGhlProductsIdRouteImport } from './routes/api.ghl.products.$id'
import { Route as ApiWebhookEventsIdRetryRouteImport } from './routes/api.webhook-events.$id.retry'
import { Route as ApiAdminProductsIdColorsRouteImport } from './routes/api.admin.products.$id.colors'
import { Route as ApiAdminProductsIdOptionsRouteImport } from './routes/api.admin.products.$id.options'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CarritoRoute = CarritoRouteImport.update({
  id: '/carrito',
  path: '/carrito',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogoRoute = CatalogoRouteImport.update({
  id: '/catalogo',
  path: '/catalogo',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const EnviosRoute = EnviosRouteImport.update({
  id: '/envios',
  path: '/envios',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritosRoute = FavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonalizarRamoRoute = PersonalizarRamoRouteImport.update({
  id: '/personalizar-ramo',
  path: '/personalizar-ramo',
  getParentRoute: () => rootRouteImport,
} as any)
const RosasEternasRoute = RosasEternasRouteImport.update({
  id: '/rosas-eternas',
  path: '/rosas-eternas',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiciosRoute = ServiciosRouteImport.update({
  id: '/servicios',
  path: '/servicios',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreNosotrosRoute = SobreNosotrosRouteImport.update({
  id: '/sobre-nosotros',
  path: '/sobre-nosotros',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMiCuentaRoute = AuthenticatedMiCuentaRouteImport.update({
  id: '/mi-cuenta',
  path: '/mi-cuenta',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiAuditLogsRoute = ApiAuditLogsRouteImport.update({
  id: '/api/audit-logs',
  path: '/api/audit-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConfirmationRoute = ApiConfirmationRouteImport.update({
  id: '/api/confirmation',
  path: '/api/confirmation',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrdersRoute = ApiOrdersRouteImport.update({
  id: '/api/orders',
  path: '/api/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProductImagesRoute = ApiProductImagesRouteImport.update({
  id: '/api/product-images',
  path: '/api/product-images',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProductsRoute = ApiProductsRouteImport.update({
  id: '/api/products',
  path: '/api/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhookEventsRoute = ApiWebhookEventsRouteImport.update({
  id: '/api/webhook-events',
  path: '/api/webhook-events',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetPasswordConfirmRoute =
  AuthResetPasswordConfirmRouteImport.update({
    id: '/reset-password-confirm',
    path: '/reset-password-confirm',
    getParentRoute: () => AuthRoute,
  } as any)
const ConfirmationOrderIdRoute = ConfirmationOrderIdRouteImport.update({
  id: '/confirmation/$orderId',
  path: '/confirmation/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const DebugGhlTestRoute = DebugGhlTestRouteImport.update({
  id: '/debug/ghl-test',
  path: '/debug/ghl-test',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalSlugRoute = LegalSlugRouteImport.update({
  id: '/legal/$slug',
  path: '/legal/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductoIdRoute = ProductoIdRouteImport.update({
  id: '/producto/$id',
  path: '/producto/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiciosIndexRoute = ServiciosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServiciosRoute,
} as any)
const ServiciosSlugRoute = ServiciosSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ServiciosRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminDashboardRoute =
  AuthenticatedAdminDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminOrdersRoute =
  AuthenticatedAdminOrdersRouteImport.update({
    id: '/orders',
    path: '/orders',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminProductsRoute =
  AuthenticatedAdminProductsRouteImport.update({
    id: '/products',
    path: '/products',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminReportsRoute =
  AuthenticatedAdminReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminWebhooksRoute =
  AuthenticatedAdminWebhooksRouteImport.update({
    id: '/webhooks',
    path: '/webhooks',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const ApiAdminDebugEnvRoute = ApiAdminDebugEnvRouteImport.update({
  id: '/api/admin/debug-env',
  path: '/api/admin/debug-env',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminDebugMetadataRoute = ApiAdminDebugMetadataRouteImport.update({
  id: '/api/admin/debug-metadata',
  path: '/api/admin/debug-metadata',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminDiagnoseMetadataRoute =
  ApiAdminDiagnoseMetadataRouteImport.update({
    id: '/api/admin/diagnose-metadata',
    path: '/api/admin/diagnose-metadata',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminPopulateMetadataRoute =
  ApiAdminPopulateMetadataRouteImport.update({
    id: '/api/admin/populate-metadata',
    path: '/api/admin/populate-metadata',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminProductsRoute = ApiAdminProductsRouteImport.update({
  id: '/api/admin/products',
  path: '/api/admin/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminSyncCatalogRoute = ApiAdminSyncCatalogRouteImport.update({
  id: '/api/admin/sync-catalog',
  path: '/api/admin/sync-catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDashboardStatsRoute = ApiDashboardStatsRouteImport.update({
  id: '/api/dashboard/stats',
  path: '/api/dashboard/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGhlProductsRoute = ApiGhlProductsRouteImport.update({
  id: '/api/ghl/products',
  path: '/api/ghl/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrdersIdRoute = ApiOrdersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiOrdersRoute,
} as any)
const ApiProductsIdRoute = ApiProductsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiProductsRoute,
} as any)
const ApiUploadProductImageRoute = ApiUploadProductImageRouteImport.update({
  id: '/api/upload/product-image',
  path: '/api/upload/product-image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksGhlOpportunityRoute =
  ApiWebhooksGhlOpportunityRouteImport.update({
    id: '/api/webhooks/ghl-opportunity',
    path: '/api/webhooks/ghl-opportunity',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiWebhooksGhlProductRoute = ApiWebhooksGhlProductRouteImport.update({
  id: '/api/webhooks/ghl-product',
  path: '/api/webhooks/ghl-product',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminOrdersIndexRoute =
  AuthenticatedAdminOrdersIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminOrdersRoute,
  } as any)
const AuthenticatedAdminOrdersIdRoute =
  AuthenticatedAdminOrdersIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminOrdersRoute,
  } as any)
const AuthenticatedAdminProductsIndexRoute =
  AuthenticatedAdminProductsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminProductsRoute,
  } as any)
const AuthenticatedAdminProductsIdRoute =
  AuthenticatedAdminProductsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminProductsRoute,
  } as any)
const AuthenticatedAdminProductsNewRoute =
  AuthenticatedAdminProductsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedAdminProductsRoute,
  } as any)
const ApiAdminProductsIdRoute = ApiAdminProductsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiAdminProductsRoute,
} as any)
const ApiGhlProductsIdRoute = ApiGhlProductsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiGhlProductsRoute,
} as any)
const ApiWebhookEventsIdRetryRoute = ApiWebhookEventsIdRetryRouteImport.update({
  id: '/$id/retry',
  path: '/$id/retry',
  getParentRoute: () => ApiWebhookEventsRoute,
} as any)
const ApiAdminProductsIdColorsRoute =
  ApiAdminProductsIdColorsRouteImport.update({
    id: '/colors',
    path: '/colors',
    getParentRoute: () => ApiAdminProductsIdRoute,
  } as any)
const ApiAdminProductsIdOptionsRoute =
  ApiAdminProductsIdOptionsRouteImport.update({
    id: '/options',
    path: '/options',
    getParentRoute: () => ApiAdminProductsIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/carrito': typeof CarritoRoute
  '/catalogo': typeof CatalogoRoute
  '/checkout': typeof CheckoutRoute
  '/contacto': typeof ContactoRoute
  '/envios': typeof EnviosRoute
  '/favoritos': typeof FavoritosRoute
  '/personalizar-ramo': typeof PersonalizarRamoRoute
  '/rosas-eternas': typeof RosasEternasRoute
  '/servicios': typeof ServiciosRouteWithChildren
  '/sobre-nosotros': typeof SobreNosotrosRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/mi-cuenta': typeof AuthenticatedMiCuentaRoute
  '/api/audit-logs': typeof ApiAuditLogsRoute
  '/api/confirmation': typeof ApiConfirmationRoute
  '/api/orders': typeof ApiOrdersRouteWithChildren
  '/api/product-images': typeof ApiProductImagesRoute
  '/api/products': typeof ApiProductsRouteWithChildren
  '/api/webhook-events': typeof ApiWebhookEventsRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/reset-password-confirm': typeof AuthResetPasswordConfirmRoute
  '/confirmation/$orderId': typeof ConfirmationOrderIdRoute
  '/debug/ghl-test': typeof DebugGhlTestRoute
  '/legal/$slug': typeof LegalSlugRoute
  '/producto/$id': typeof ProductoIdRoute
  '/servicios/$slug': typeof ServiciosSlugRoute
  '/servicios/': typeof ServiciosIndexRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/orders': typeof AuthenticatedAdminOrdersRouteWithChildren
  '/admin/products': typeof AuthenticatedAdminProductsRouteWithChildren
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/webhooks': typeof AuthenticatedAdminWebhooksRoute
  '/api/admin/debug-env': typeof ApiAdminDebugEnvRoute
  '/api/admin/debug-metadata': typeof ApiAdminDebugMetadataRoute
  '/api/admin/diagnose-metadata': typeof ApiAdminDiagnoseMetadataRoute
  '/api/admin/populate-metadata': typeof ApiAdminPopulateMetadataRoute
  '/api/admin/products': typeof ApiAdminProductsRouteWithChildren
  '/api/admin/sync-catalog': typeof ApiAdminSyncCatalogRoute
  '/api/dashboard/stats': typeof ApiDashboardStatsRoute
  '/api/ghl/products': typeof ApiGhlProductsRouteWithChildren
  '/api/orders/$id': typeof ApiOrdersIdRoute
  '/api/products/$id': typeof ApiProductsIdRoute
  '/api/upload/product-image': typeof ApiUploadProductImageRoute
  '/api/webhooks/ghl-opportunity': typeof ApiWebhooksGhlOpportunityRoute
  '/api/webhooks/ghl-product': typeof ApiWebhooksGhlProductRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/orders/$id': typeof AuthenticatedAdminOrdersIdRoute
  '/admin/products/$id': typeof AuthenticatedAdminProductsIdRoute
  '/admin/products/new': typeof AuthenticatedAdminProductsNewRoute
  '/api/admin/products/$id': typeof ApiAdminProductsIdRouteWithChildren
  '/api/ghl/products/$id': typeof ApiGhlProductsIdRoute
  '/api/webhook-events/$id/retry': typeof ApiWebhookEventsIdRetryRoute
  '/admin/orders/': typeof AuthenticatedAdminOrdersIndexRoute
  '/admin/products/': typeof AuthenticatedAdminProductsIndexRoute
  '/api/admin/products/$id/colors': typeof ApiAdminProductsIdColorsRoute
  '/api/admin/products/$id/options': typeof ApiAdminProductsIdOptionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/carrito': typeof CarritoRoute
  '/catalogo': typeof CatalogoRoute
  '/checkout': typeof CheckoutRoute
  '/contacto': typeof ContactoRoute
  '/envios': typeof EnviosRoute
  '/favoritos': typeof FavoritosRoute
  '/personalizar-ramo': typeof PersonalizarRamoRoute
  '/rosas-eternas': typeof RosasEternasRoute
  '/sobre-nosotros': typeof SobreNosotrosRoute
  '/mi-cuenta': typeof AuthenticatedMiCuentaRoute
  '/api/audit-logs': typeof ApiAuditLogsRoute
  '/api/confirmation': typeof ApiConfirmationRoute
  '/api/orders': typeof ApiOrdersRouteWithChildren
  '/api/product-images': typeof ApiProductImagesRoute
  '/api/products': typeof ApiProductsRouteWithChildren
  '/api/webhook-events': typeof ApiWebhookEventsRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/reset-password-confirm': typeof AuthResetPasswordConfirmRoute
  '/confirmation/$orderId': typeof ConfirmationOrderIdRoute
  '/debug/ghl-test': typeof DebugGhlTestRoute
  '/legal/$slug': typeof LegalSlugRoute
  '/producto/$id': typeof ProductoIdRoute
  '/servicios/$slug': typeof ServiciosSlugRoute
  '/servicios': typeof ServiciosIndexRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/webhooks': typeof AuthenticatedAdminWebhooksRoute
  '/api/admin/debug-env': typeof ApiAdminDebugEnvRoute
  '/api/admin/debug-metadata': typeof ApiAdminDebugMetadataRoute
  '/api/admin/diagnose-metadata': typeof ApiAdminDiagnoseMetadataRoute
  '/api/admin/populate-metadata': typeof ApiAdminPopulateMetadataRoute
  '/api/admin/products': typeof ApiAdminProductsRouteWithChildren
  '/api/admin/sync-catalog': typeof ApiAdminSyncCatalogRoute
  '/api/dashboard/stats': typeof ApiDashboardStatsRoute
  '/api/ghl/products': typeof ApiGhlProductsRouteWithChildren
  '/api/orders/$id': typeof ApiOrdersIdRoute
  '/api/products/$id': typeof ApiProductsIdRoute
  '/api/upload/product-image': typeof ApiUploadProductImageRoute
  '/api/webhooks/ghl-opportunity': typeof ApiWebhooksGhlOpportunityRoute
  '/api/webhooks/ghl-product': typeof ApiWebhooksGhlProductRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/orders/$id': typeof AuthenticatedAdminOrdersIdRoute
  '/admin/products/$id': typeof AuthenticatedAdminProductsIdRoute
  '/admin/products/new': typeof AuthenticatedAdminProductsNewRoute
  '/api/admin/products/$id': typeof ApiAdminProductsIdRouteWithChildren
  '/api/ghl/products/$id': typeof ApiGhlProductsIdRoute
  '/api/webhook-events/$id/retry': typeof ApiWebhookEventsIdRetryRoute
  '/admin/orders': typeof AuthenticatedAdminOrdersIndexRoute
  '/admin/products': typeof AuthenticatedAdminProductsIndexRoute
  '/api/admin/products/$id/colors': typeof ApiAdminProductsIdColorsRoute
  '/api/admin/products/$id/options': typeof ApiAdminProductsIdOptionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/carrito': typeof CarritoRoute
  '/catalogo': typeof CatalogoRoute
  '/checkout': typeof CheckoutRoute
  '/contacto': typeof ContactoRoute
  '/envios': typeof EnviosRoute
  '/favoritos': typeof FavoritosRoute
  '/personalizar-ramo': typeof PersonalizarRamoRoute
  '/rosas-eternas': typeof RosasEternasRoute
  '/servicios': typeof ServiciosRouteWithChildren
  '/sobre-nosotros': typeof SobreNosotrosRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/mi-cuenta': typeof AuthenticatedMiCuentaRoute
  '/api/audit-logs': typeof ApiAuditLogsRoute
  '/api/confirmation': typeof ApiConfirmationRoute
  '/api/orders': typeof ApiOrdersRouteWithChildren
  '/api/product-images': typeof ApiProductImagesRoute
  '/api/products': typeof ApiProductsRouteWithChildren
  '/api/webhook-events': typeof ApiWebhookEventsRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/reset-password-confirm': typeof AuthResetPasswordConfirmRoute
  '/confirmation/$orderId': typeof ConfirmationOrderIdRoute
  '/debug/ghl-test': typeof DebugGhlTestRoute
  '/legal/$slug': typeof LegalSlugRoute
  '/producto/$id': typeof ProductoIdRoute
  '/servicios/$slug': typeof ServiciosSlugRoute
  '/servicios/': typeof ServiciosIndexRoute
  '/_authenticated/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/_authenticated/admin/orders': typeof AuthenticatedAdminOrdersRouteWithChildren
  '/_authenticated/admin/products': typeof AuthenticatedAdminProductsRouteWithChildren
  '/_authenticated/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/webhooks': typeof AuthenticatedAdminWebhooksRoute
  '/api/admin/debug-env': typeof ApiAdminDebugEnvRoute
  '/api/admin/debug-metadata': typeof ApiAdminDebugMetadataRoute
  '/api/admin/diagnose-metadata': typeof ApiAdminDiagnoseMetadataRoute
  '/api/admin/populate-metadata': typeof ApiAdminPopulateMetadataRoute
  '/api/admin/products': typeof ApiAdminProductsRouteWithChildren
  '/api/admin/sync-catalog': typeof ApiAdminSyncCatalogRoute
  '/api/dashboard/stats': typeof ApiDashboardStatsRoute
  '/api/ghl/products': typeof ApiGhlProductsRouteWithChildren
  '/api/orders/$id': typeof ApiOrdersIdRoute
  '/api/products/$id': typeof ApiProductsIdRoute
  '/api/upload/product-image': typeof ApiUploadProductImageRoute
  '/api/webhooks/ghl-opportunity': typeof ApiWebhooksGhlOpportunityRoute
  '/api/webhooks/ghl-product': typeof ApiWebhooksGhlProductRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/orders/$id': typeof AuthenticatedAdminOrdersIdRoute
  '/_authenticated/admin/products/$id': typeof AuthenticatedAdminProductsIdRoute
  '/_authenticated/admin/products/new': typeof AuthenticatedAdminProductsNewRoute
  '/api/admin/products/$id': typeof ApiAdminProductsIdRouteWithChildren
  '/api/ghl/products/$id': typeof ApiGhlProductsIdRoute
  '/api/webhook-events/$id/retry': typeof ApiWebhookEventsIdRetryRoute
  '/_authenticated/admin/orders/': typeof AuthenticatedAdminOrdersIndexRoute
  '/_authenticated/admin/products/': typeof AuthenticatedAdminProductsIndexRoute
  '/api/admin/products/$id/colors': typeof ApiAdminProductsIdColorsRoute
  '/api/admin/products/$id/options': typeof ApiAdminProductsIdOptionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/carrito'
    | '/catalogo'
    | '/checkout'
    | '/contacto'
    | '/envios'
    | '/favoritos'
    | '/personalizar-ramo'
    | '/rosas-eternas'
    | '/servicios'
    | '/sobre-nosotros'
    | '/admin'
    | '/mi-cuenta'
    | '/api/audit-logs'
    | '/api/confirmation'
    | '/api/orders'
    | '/api/product-images'
    | '/api/products'
    | '/api/webhook-events'
    | '/auth/callback'
    | '/auth/reset-password'
    | '/auth/reset-password-confirm'
    | '/confirmation/$orderId'
    | '/debug/ghl-test'
    | '/legal/$slug'
    | '/producto/$id'
    | '/servicios/$slug'
    | '/servicios/'
    | '/admin/dashboard'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/webhooks'
    | '/api/admin/debug-env'
    | '/api/admin/debug-metadata'
    | '/api/admin/diagnose-metadata'
    | '/api/admin/populate-metadata'
    | '/api/admin/products'
    | '/api/admin/sync-catalog'
    | '/api/dashboard/stats'
    | '/api/ghl/products'
    | '/api/orders/$id'
    | '/api/products/$id'
    | '/api/upload/product-image'
    | '/api/webhooks/ghl-opportunity'
    | '/api/webhooks/ghl-product'
    | '/admin/'
    | '/admin/orders/$id'
    | '/admin/products/$id'
    | '/admin/products/new'
    | '/api/admin/products/$id'
    | '/api/ghl/products/$id'
    | '/api/webhook-events/$id/retry'
    | '/admin/orders/'
    | '/admin/products/'
    | '/api/admin/products/$id/colors'
    | '/api/admin/products/$id/options'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/carrito'
    | '/catalogo'
    | '/checkout'
    | '/contacto'
    | '/envios'
    | '/favoritos'
    | '/personalizar-ramo'
    | '/rosas-eternas'
    | '/sobre-nosotros'
    | '/mi-cuenta'
    | '/api/audit-logs'
    | '/api/confirmation'
    | '/api/orders'
    | '/api/product-images'
    | '/api/products'
    | '/api/webhook-events'
    | '/auth/callback'
    | '/auth/reset-password'
    | '/auth/reset-password-confirm'
    | '/confirmation/$orderId'
    | '/debug/ghl-test'
    | '/legal/$slug'
    | '/producto/$id'
    | '/servicios/$slug'
    | '/servicios'
    | '/admin/dashboard'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/webhooks'
    | '/api/admin/debug-env'
    | '/api/admin/debug-metadata'
    | '/api/admin/diagnose-metadata'
    | '/api/admin/populate-metadata'
    | '/api/admin/products'
    | '/api/admin/sync-catalog'
    | '/api/dashboard/stats'
    | '/api/ghl/products'
    | '/api/orders/$id'
    | '/api/products/$id'
    | '/api/upload/product-image'
    | '/api/webhooks/ghl-opportunity'
    | '/api/webhooks/ghl-product'
    | '/admin'
    | '/admin/orders/$id'
    | '/admin/products/$id'
    | '/admin/products/new'
    | '/api/admin/products/$id'
    | '/api/ghl/products/$id'
    | '/api/webhook-events/$id/retry'
    | '/admin/orders'
    | '/admin/products'
    | '/api/admin/products/$id/colors'
    | '/api/admin/products/$id/options'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/carrito'
    | '/catalogo'
    | '/checkout'
    | '/contacto'
    | '/envios'
    | '/favoritos'
    | '/personalizar-ramo'
    | '/rosas-eternas'
    | '/servicios'
    | '/sobre-nosotros'
    | '/_authenticated/admin'
    | '/_authenticated/mi-cuenta'
    | '/api/audit-logs'
    | '/api/confirmation'
    | '/api/orders'
    | '/api/product-images'
    | '/api/products'
    | '/api/webhook-events'
    | '/auth/callback'
    | '/auth/reset-password'
    | '/auth/reset-password-confirm'
    | '/confirmation/$orderId'
    | '/debug/ghl-test'
    | '/legal/$slug'
    | '/producto/$id'
    | '/servicios/$slug'
    | '/servicios/'
    | '/_authenticated/admin/dashboard'
    | '/_authenticated/admin/orders'
    | '/_authenticated/admin/products'
    | '/_authenticated/admin/reports'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/webhooks'
    | '/api/admin/debug-env'
    | '/api/admin/debug-metadata'
    | '/api/admin/diagnose-metadata'
    | '/api/admin/populate-metadata'
    | '/api/admin/products'
    | '/api/admin/sync-catalog'
    | '/api/dashboard/stats'
    | '/api/ghl/products'
    | '/api/orders/$id'
    | '/api/products/$id'
    | '/api/upload/product-image'
    | '/api/webhooks/ghl-opportunity'
    | '/api/webhooks/ghl-product'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/orders/$id'
    | '/_authenticated/admin/products/$id'
    | '/_authenticated/admin/products/new'
    | '/api/admin/products/$id'
    | '/api/ghl/products/$id'
    | '/api/webhook-events/$id/retry'
    | '/_authenticated/admin/orders/'
    | '/_authenticated/admin/products/'
    | '/api/admin/products/$id/colors'
    | '/api/admin/products/$id/options'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  CarritoRoute: typeof CarritoRoute
  CatalogoRoute: typeof CatalogoRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactoRoute: typeof ContactoRoute
  EnviosRoute: typeof EnviosRoute
  FavoritosRoute: typeof FavoritosRoute
  PersonalizarRamoRoute: typeof PersonalizarRamoRoute
  RosasEternasRoute: typeof RosasEternasRoute
  ServiciosRoute: typeof ServiciosRouteWithChildren
  SobreNosotrosRoute: typeof SobreNosotrosRoute
  ApiAuditLogsRoute: typeof ApiAuditLogsRoute
  ApiConfirmationRoute: typeof ApiConfirmationRoute
  ApiOrdersRoute: typeof ApiOrdersRouteWithChildren
  ApiProductImagesRoute: typeof ApiProductImagesRoute
  ApiProductsRoute: typeof ApiProductsRouteWithChildren
  ApiWebhookEventsRoute: typeof ApiWebhookEventsRouteWithChildren
  ConfirmationOrderIdRoute: typeof ConfirmationOrderIdRoute
  DebugGhlTestRoute: typeof DebugGhlTestRoute
  LegalSlugRoute: typeof LegalSlugRoute
  ProductoIdRoute: typeof ProductoIdRoute
  ApiAdminDebugEnvRoute: typeof ApiAdminDebugEnvRoute
  ApiAdminDebugMetadataRoute: typeof ApiAdminDebugMetadataRoute
  ApiAdminDiagnoseMetadataRoute: typeof ApiAdminDiagnoseMetadataRoute
  ApiAdminPopulateMetadataRoute: typeof ApiAdminPopulateMetadataRoute
  ApiAdminProductsRoute: typeof ApiAdminProductsRouteWithChildren
  ApiAdminSyncCatalogRoute: typeof ApiAdminSyncCatalogRoute
  ApiDashboardStatsRoute: typeof ApiDashboardStatsRoute
  ApiGhlProductsRoute: typeof ApiGhlProductsRouteWithChildren
  ApiUploadProductImageRoute: typeof ApiUploadProductImageRoute
  ApiWebhooksGhlOpportunityRoute: typeof ApiWebhooksGhlOpportunityRoute
  ApiWebhooksGhlProductRoute: typeof ApiWebhooksGhlProductRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carrito': {
      id: '/carrito'
      path: '/carrito'
      fullPath: '/carrito'
      preLoaderRoute: typeof CarritoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogo': {
      id: '/catalogo'
      path: '/catalogo'
      fullPath: '/catalogo'
      preLoaderRoute: typeof CatalogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/envios': {
      id: '/envios'
      path: '/envios'
      fullPath: '/envios'
      preLoaderRoute: typeof EnviosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favoritos': {
      id: '/favoritos'
      path: '/favoritos'
      fullPath: '/favoritos'
      preLoaderRoute: typeof FavoritosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personalizar-ramo': {
      id: '/personalizar-ramo'
      path: '/personalizar-ramo'
      fullPath: '/personalizar-ramo'
      preLoaderRoute: typeof PersonalizarRamoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rosas-eternas': {
      id: '/rosas-eternas'
      path: '/rosas-eternas'
      fullPath: '/rosas-eternas'
      preLoaderRoute: typeof RosasEternasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicios': {
      id: '/servicios'
      path: '/servicios'
      fullPath: '/servicios'
      preLoaderRoute: typeof ServiciosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre-nosotros': {
      id: '/sobre-nosotros'
      path: '/sobre-nosotros'
      fullPath: '/sobre-nosotros'
      preLoaderRoute: typeof SobreNosotrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mi-cuenta': {
      id: '/_authenticated/mi-cuenta'
      path: '/mi-cuenta'
      fullPath: '/mi-cuenta'
      preLoaderRoute: typeof AuthenticatedMiCuentaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/audit-logs': {
      id: '/api/audit-logs'
      path: '/api/audit-logs'
      fullPath: '/api/audit-logs'
      preLoaderRoute: typeof ApiAuditLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/confirmation': {
      id: '/api/confirmation'
      path: '/api/confirmation'
      fullPath: '/api/confirmation'
      preLoaderRoute: typeof ApiConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/orders': {
      id: '/api/orders'
      path: '/api/orders'
      fullPath: '/api/orders'
      preLoaderRoute: typeof ApiOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/product-images': {
      id: '/api/product-images'
      path: '/api/product-images'
      fullPath: '/api/product-images'
      preLoaderRoute: typeof ApiProductImagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/products': {
      id: '/api/products'
      path: '/api/products'
      fullPath: '/api/products'
      preLoaderRoute: typeof ApiProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhook-events': {
      id: '/api/webhook-events'
      path: '/api/webhook-events'
      fullPath: '/api/webhook-events'
      preLoaderRoute: typeof ApiWebhookEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/reset-password-confirm': {
      id: '/auth/reset-password-confirm'
      path: '/reset-password-confirm'
      fullPath: '/auth/reset-password-confirm'
      preLoaderRoute: typeof AuthResetPasswordConfirmRouteImport
      parentRoute: typeof AuthRoute
    }
    '/confirmation/$orderId': {
      id: '/confirmation/$orderId'
      path: '/confirmation/$orderId'
      fullPath: '/confirmation/$orderId'
      preLoaderRoute: typeof ConfirmationOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debug/ghl-test': {
      id: '/debug/ghl-test'
      path: '/debug/ghl-test'
      fullPath: '/debug/ghl-test'
      preLoaderRoute: typeof DebugGhlTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/$slug': {
      id: '/legal/$slug'
      path: '/legal/$slug'
      fullPath: '/legal/$slug'
      preLoaderRoute: typeof LegalSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/producto/$id': {
      id: '/producto/$id'
      path: '/producto/$id'
      fullPath: '/producto/$id'
      preLoaderRoute: typeof ProductoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicios/': {
      id: '/servicios/'
      path: '/'
      fullPath: '/servicios/'
      preLoaderRoute: typeof ServiciosIndexRouteImport
      parentRoute: typeof ServiciosRoute
    }
    '/servicios/$slug': {
      id: '/servicios/$slug'
      path: '/$slug'
      fullPath: '/servicios/$slug'
      preLoaderRoute: typeof ServiciosSlugRouteImport
      parentRoute: typeof ServiciosRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/dashboard': {
      id: '/_authenticated/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AuthenticatedAdminDashboardRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/orders': {
      id: '/_authenticated/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AuthenticatedAdminOrdersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/products': {
      id: '/_authenticated/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AuthenticatedAdminProductsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/reports': {
      id: '/_authenticated/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AuthenticatedAdminReportsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/webhooks': {
      id: '/_authenticated/admin/webhooks'
      path: '/webhooks'
      fullPath: '/admin/webhooks'
      preLoaderRoute: typeof AuthenticatedAdminWebhooksRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/api/admin/debug-env': {
      id: '/api/admin/debug-env'
      path: '/api/admin/debug-env'
      fullPath: '/api/admin/debug-env'
      preLoaderRoute: typeof ApiAdminDebugEnvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/debug-metadata': {
      id: '/api/admin/debug-metadata'
      path: '/api/admin/debug-metadata'
      fullPath: '/api/admin/debug-metadata'
      preLoaderRoute: typeof ApiAdminDebugMetadataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/diagnose-metadata': {
      id: '/api/admin/diagnose-metadata'
      path: '/api/admin/diagnose-metadata'
      fullPath: '/api/admin/diagnose-metadata'
      preLoaderRoute: typeof ApiAdminDiagnoseMetadataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/populate-metadata': {
      id: '/api/admin/populate-metadata'
      path: '/api/admin/populate-metadata'
      fullPath: '/api/admin/populate-metadata'
      preLoaderRoute: typeof ApiAdminPopulateMetadataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/products': {
      id: '/api/admin/products'
      path: '/api/admin/products'
      fullPath: '/api/admin/products'
      preLoaderRoute: typeof ApiAdminProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/sync-catalog': {
      id: '/api/admin/sync-catalog'
      path: '/api/admin/sync-catalog'
      fullPath: '/api/admin/sync-catalog'
      preLoaderRoute: typeof ApiAdminSyncCatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dashboard/stats': {
      id: '/api/dashboard/stats'
      path: '/api/dashboard/stats'
      fullPath: '/api/dashboard/stats'
      preLoaderRoute: typeof ApiDashboardStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ghl/products': {
      id: '/api/ghl/products'
      path: '/api/ghl/products'
      fullPath: '/api/ghl/products'
      preLoaderRoute: typeof ApiGhlProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/orders/$id': {
      id: '/api/orders/$id'
      path: '/$id'
      fullPath: '/api/orders/$id'
      preLoaderRoute: typeof ApiOrdersIdRouteImport
      parentRoute: typeof ApiOrdersRoute
    }
    '/api/products/$id': {
      id: '/api/products/$id'
      path: '/$id'
      fullPath: '/api/products/$id'
      preLoaderRoute: typeof ApiProductsIdRouteImport
      parentRoute: typeof ApiProductsRoute
    }
    '/api/upload/product-image': {
      id: '/api/upload/product-image'
      path: '/api/upload/product-image'
      fullPath: '/api/upload/product-image'
      preLoaderRoute: typeof ApiUploadProductImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/ghl-opportunity': {
      id: '/api/webhooks/ghl-opportunity'
      path: '/api/webhooks/ghl-opportunity'
      fullPath: '/api/webhooks/ghl-opportunity'
      preLoaderRoute: typeof ApiWebhooksGhlOpportunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/ghl-product': {
      id: '/api/webhooks/ghl-product'
      path: '/api/webhooks/ghl-product'
      fullPath: '/api/webhooks/ghl-product'
      preLoaderRoute: typeof ApiWebhooksGhlProductRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/orders/': {
      id: '/_authenticated/admin/orders/'
      path: '/'
      fullPath: '/admin/orders/'
      preLoaderRoute: typeof AuthenticatedAdminOrdersIndexRouteImport
      parentRoute: typeof AuthenticatedAdminOrdersRoute
    }
    '/_authenticated/admin/orders/$id': {
      id: '/_authenticated/admin/orders/$id'
      path: '/$id'
      fullPath: '/admin/orders/$id'
      preLoaderRoute: typeof AuthenticatedAdminOrdersIdRouteImport
      parentRoute: typeof AuthenticatedAdminOrdersRoute
    }
    '/_authenticated/admin/products/': {
      id: '/_authenticated/admin/products/'
      path: '/'
      fullPath: '/admin/products/'
      preLoaderRoute: typeof AuthenticatedAdminProductsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminProductsRoute
    }
    '/_authenticated/admin/products/$id': {
      id: '/_authenticated/admin/products/$id'
      path: '/$id'
      fullPath: '/admin/products/$id'
      preLoaderRoute: typeof AuthenticatedAdminProductsIdRouteImport
      parentRoute: typeof AuthenticatedAdminProductsRoute
    }
    '/_authenticated/admin/products/new': {
      id: '/_authenticated/admin/products/new'
      path: '/new'
      fullPath: '/admin/products/new'
      preLoaderRoute: typeof AuthenticatedAdminProductsNewRouteImport
      parentRoute: typeof AuthenticatedAdminProductsRoute
    }
    '/api/admin/products/$id': {
      id: '/api/admin/products/$id'
      path: '/$id'
      fullPath: '/api/admin/products/$id'
      preLoaderRoute: typeof ApiAdminProductsIdRouteImport
      parentRoute: typeof ApiAdminProductsRoute
    }
    '/api/ghl/products/$id': {
      id: '/api/ghl/products/$id'
      path: '/$id'
      fullPath: '/api/ghl/products/$id'
      preLoaderRoute: typeof ApiGhlProductsIdRouteImport
      parentRoute: typeof ApiGhlProductsRoute
    }
    '/api/webhook-events/$id/retry': {
      id: '/api/webhook-events/$id/retry'
      path: '/$id/retry'
      fullPath: '/api/webhook-events/$id/retry'
      preLoaderRoute: typeof ApiWebhookEventsIdRetryRouteImport
      parentRoute: typeof ApiWebhookEventsRoute
    }
    '/api/admin/products/$id/colors': {
      id: '/api/admin/products/$id/colors'
      path: '/colors'
      fullPath: '/api/admin/products/$id/colors'
      preLoaderRoute: typeof ApiAdminProductsIdColorsRouteImport
      parentRoute: typeof ApiAdminProductsIdRoute
    }
    '/api/admin/products/$id/options': {
      id: '/api/admin/products/$id/options'
      path: '/options'
      fullPath: '/api/admin/products/$id/options'
      preLoaderRoute: typeof ApiAdminProductsIdOptionsRouteImport
      parentRoute: typeof ApiAdminProductsIdRoute
    }
  }
}

interface AuthenticatedAdminOrdersRouteChildren {
  AuthenticatedAdminOrdersIdRoute: typeof AuthenticatedAdminOrdersIdRoute
  AuthenticatedAdminOrdersIndexRoute: typeof AuthenticatedAdminOrdersIndexRoute
}

const AuthenticatedAdminOrdersRouteChildren: AuthenticatedAdminOrdersRouteChildren =
  {
    AuthenticatedAdminOrdersIdRoute: AuthenticatedAdminOrdersIdRoute,
    AuthenticatedAdminOrdersIndexRoute: AuthenticatedAdminOrdersIndexRoute,
  }

const AuthenticatedAdminOrdersRouteWithChildren =
  AuthenticatedAdminOrdersRoute._addFileChildren(
    AuthenticatedAdminOrdersRouteChildren,
  )

interface AuthenticatedAdminProductsRouteChildren {
  AuthenticatedAdminProductsIdRoute: typeof AuthenticatedAdminProductsIdRoute
  AuthenticatedAdminProductsNewRoute: typeof AuthenticatedAdminProductsNewRoute
  AuthenticatedAdminProductsIndexRoute: typeof AuthenticatedAdminProductsIndexRoute
}

const AuthenticatedAdminProductsRouteChildren: AuthenticatedAdminProductsRouteChildren =
  {
    AuthenticatedAdminProductsIdRoute: AuthenticatedAdminProductsIdRoute,
    AuthenticatedAdminProductsNewRoute: AuthenticatedAdminProductsNewRoute,
    AuthenticatedAdminProductsIndexRoute: AuthenticatedAdminProductsIndexRoute,
  }

const AuthenticatedAdminProductsRouteWithChildren =
  AuthenticatedAdminProductsRoute._addFileChildren(
    AuthenticatedAdminProductsRouteChildren,
  )

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminDashboardRoute: typeof AuthenticatedAdminDashboardRoute
  AuthenticatedAdminOrdersRoute: typeof AuthenticatedAdminOrdersRouteWithChildren
  AuthenticatedAdminProductsRoute: typeof AuthenticatedAdminProductsRouteWithChildren
  AuthenticatedAdminReportsRoute: typeof AuthenticatedAdminReportsRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminWebhooksRoute: typeof AuthenticatedAdminWebhooksRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminDashboardRoute: AuthenticatedAdminDashboardRoute,
    AuthenticatedAdminOrdersRoute: AuthenticatedAdminOrdersRouteWithChildren,
    AuthenticatedAdminProductsRoute:
      AuthenticatedAdminProductsRouteWithChildren,
    AuthenticatedAdminReportsRoute: AuthenticatedAdminReportsRoute,
    AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
    AuthenticatedAdminWebhooksRoute: AuthenticatedAdminWebhooksRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedMiCuentaRoute: typeof AuthenticatedMiCuentaRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedMiCuentaRoute: AuthenticatedMiCuentaRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthResetPasswordConfirmRoute: typeof AuthResetPasswordConfirmRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthResetPasswordConfirmRoute: AuthResetPasswordConfirmRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface ServiciosRouteChildren {
  ServiciosSlugRoute: typeof ServiciosSlugRoute
  ServiciosIndexRoute: typeof ServiciosIndexRoute
}

const ServiciosRouteChildren: ServiciosRouteChildren = {
  ServiciosSlugRoute: ServiciosSlugRoute,
  ServiciosIndexRoute: ServiciosIndexRoute,
}

const ServiciosRouteWithChildren = ServiciosRoute._addFileChildren(
  ServiciosRouteChildren,
)

interface ApiOrdersRouteChildren {
  ApiOrdersIdRoute: typeof ApiOrdersIdRoute
}

const ApiOrdersRouteChildren: ApiOrdersRouteChildren = {
  ApiOrdersIdRoute: ApiOrdersIdRoute,
}

const ApiOrdersRouteWithChildren = ApiOrdersRoute._addFileChildren(
  ApiOrdersRouteChildren,
)

interface ApiProductsRouteChildren {
  ApiProductsIdRoute: typeof ApiProductsIdRoute
}

const ApiProductsRouteChildren: ApiProductsRouteChildren = {
  ApiProductsIdRoute: ApiProductsIdRoute,
}

const ApiProductsRouteWithChildren = ApiProductsRoute._addFileChildren(
  ApiProductsRouteChildren,
)

interface ApiWebhookEventsRouteChildren {
  ApiWebhookEventsIdRetryRoute: typeof ApiWebhookEventsIdRetryRoute
}

const ApiWebhookEventsRouteChildren: ApiWebhookEventsRouteChildren = {
  ApiWebhookEventsIdRetryRoute: ApiWebhookEventsIdRetryRoute,
}

const ApiWebhookEventsRouteWithChildren =
  ApiWebhookEventsRoute._addFileChildren(ApiWebhookEventsRouteChildren)

interface ApiAdminProductsIdRouteChildren {
  ApiAdminProductsIdColorsRoute: typeof ApiAdminProductsIdColorsRoute
  ApiAdminProductsIdOptionsRoute: typeof ApiAdminProductsIdOptionsRoute
}

const ApiAdminProductsIdRouteChildren: ApiAdminProductsIdRouteChildren = {
  ApiAdminProductsIdColorsRoute: ApiAdminProductsIdColorsRoute,
  ApiAdminProductsIdOptionsRoute: ApiAdminProductsIdOptionsRoute,
}

const ApiAdminProductsIdRouteWithChildren =
  ApiAdminProductsIdRoute._addFileChildren(ApiAdminProductsIdRouteChildren)

interface ApiAdminProductsRouteChildren {
  ApiAdminProductsIdRoute: typeof ApiAdminProductsIdRouteWithChildren
}

const ApiAdminProductsRouteChildren: ApiAdminProductsRouteChildren = {
  ApiAdminProductsIdRoute: ApiAdminProductsIdRouteWithChildren,
}

const ApiAdminProductsRouteWithChildren =
  ApiAdminProductsRoute._addFileChildren(ApiAdminProductsRouteChildren)

interface ApiGhlProductsRouteChildren {
  ApiGhlProductsIdRoute: typeof ApiGhlProductsIdRoute
}

const ApiGhlProductsRouteChildren: ApiGhlProductsRouteChildren = {
  ApiGhlProductsIdRoute: ApiGhlProductsIdRoute,
}

const ApiGhlProductsRouteWithChildren = ApiGhlProductsRoute._addFileChildren(
  ApiGhlProductsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  CarritoRoute: CarritoRoute,
  CatalogoRoute: CatalogoRoute,
  CheckoutRoute: CheckoutRoute,
  ContactoRoute: ContactoRoute,
  EnviosRoute: EnviosRoute,
  FavoritosRoute: FavoritosRoute,
  PersonalizarRamoRoute: PersonalizarRamoRoute,
  RosasEternasRoute: RosasEternasRoute,
  ServiciosRoute: ServiciosRouteWithChildren,
  SobreNosotrosRoute: SobreNosotrosRoute,
  ApiAuditLogsRoute: ApiAuditLogsRoute,
  ApiConfirmationRoute: ApiConfirmationRoute,
  ApiOrdersRoute: ApiOrdersRouteWithChildren,
  ApiProductImagesRoute: ApiProductImagesRoute,
  ApiProductsRoute: ApiProductsRouteWithChildren,
  ApiWebhookEventsRoute: ApiWebhookEventsRouteWithChildren,
  ConfirmationOrderIdRoute: ConfirmationOrderIdRoute,
  DebugGhlTestRoute: DebugGhlTestRoute,
  LegalSlugRoute: LegalSlugRoute,
  ProductoIdRoute: ProductoIdRoute,
  ApiAdminDebugEnvRoute: ApiAdminDebugEnvRoute,
  ApiAdminDebugMetadataRoute: ApiAdminDebugMetadataRoute,
  ApiAdminDiagnoseMetadataRoute: ApiAdminDiagnoseMetadataRoute,
  ApiAdminPopulateMetadataRoute: ApiAdminPopulateMetadataRoute,
  ApiAdminProductsRoute: ApiAdminProductsRouteWithChildren,
  ApiAdminSyncCatalogRoute: ApiAdminSyncCatalogRoute,
  ApiDashboardStatsRoute: ApiDashboardStatsRoute,
  ApiGhlProductsRoute: ApiGhlProductsRouteWithChildren,
  ApiUploadProductImageRoute: ApiUploadProductImageRoute,
  ApiWebhooksGhlOpportunityRoute: ApiWebhooksGhlOpportunityRoute,
  ApiWebhooksGhlProductRoute: ApiWebhooksGhlProductRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
