/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CarritoRouteImport } from './routes/carrito'
import { Route as CatalogoRouteImport } from './routes/catalogo'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as EnviosRouteImport } from './routes/envios'
import { Route as FavoritosRouteImport } from './routes/favoritos'
import { Route as PersonalizarRamoRouteImport } from './routes/personalizar-ramo'
import { Route as RosasEternasRouteImport } from './routes/rosas-eternas'
import { Route as ServiciosRouteImport } from './routes/servicios'
import { Route as SobreNosotrosRouteImport } from './routes/sobre-nosotros'
import { Route as AuthenticatedMiCuentaRouteImport } from './routes/_authenticated/mi-cuenta'
import { Route as DebugGhlTestRouteImport } from './routes/debug.ghl-test'
import { Route as LegalSlugRouteImport } from './routes/legal.$slug'
import { Route as ProductoIdRouteImport } from './routes/producto.$id'
import { Route as ServiciosIndexRouteImport } from './routes/servicios.index'
import { Route as ServiciosSlugRouteImport } from './routes/servicios.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CarritoRoute = CarritoRouteImport.update({
  id: '/carrito',
  path: '/carrito',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogoRoute = CatalogoRouteImport.update({
  id: '/catalogo',
  path: '/catalogo',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const EnviosRoute = EnviosRouteImport.update({
  id: '/envios',
  path: '/envios',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritosRoute = FavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonalizarRamoRoute = PersonalizarRamoRouteImport.update({
  id: '/personalizar-ramo',
  path: '/personalizar-ramo',
  getParentRoute: () => rootRouteImport,
} as any)
const RosasEternasRoute = RosasEternasRouteImport.update({
  id: '/rosas-eternas',
  path: '/rosas-eternas',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiciosRoute = ServiciosRouteImport.update({
  id: '/servicios',
  path: '/servicios',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreNosotrosRoute = SobreNosotrosRouteImport.update({
  id: '/sobre-nosotros',
  path: '/sobre-nosotros',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMiCuentaRoute = AuthenticatedMiCuentaRouteImport.update({
  id: '/mi-cuenta',
  path: '/mi-cuenta',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const DebugGhlTestRoute = DebugGhlTestRouteImport.update({
  id: '/debug/ghl-test',
  path: '/debug/ghl-test',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalSlugRoute = LegalSlugRouteImport.update({
  id: '/legal/$slug',
  path: '/legal/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductoIdRoute = ProductoIdRouteImport.update({
  id: '/producto/$id',
  path: '/producto/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiciosIndexRoute = ServiciosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServiciosRoute,
} as any)
const ServiciosSlugRoute = ServiciosSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ServiciosRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/carrito': typeof CarritoRoute
  '/catalogo': typeof CatalogoRoute
  '/contacto': typeof ContactoRoute
  '/envios': typeof EnviosRoute
  '/favoritos': typeof FavoritosRoute
  '/personalizar-ramo': typeof PersonalizarRamoRoute
  '/rosas-eternas': typeof RosasEternasRoute
  '/servicios': typeof ServiciosRouteWithChildren
  '/sobre-nosotros': typeof SobreNosotrosRoute
  '/mi-cuenta': typeof AuthenticatedMiCuentaRoute
  '/debug/ghl-test': typeof DebugGhlTestRoute
  '/legal/$slug': typeof LegalSlugRoute
  '/producto/$id': typeof ProductoIdRoute
  '/servicios/$slug': typeof ServiciosSlugRoute
  '/servicios/': typeof ServiciosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/carrito': typeof CarritoRoute
  '/catalogo': typeof CatalogoRoute
  '/contacto': typeof ContactoRoute
  '/envios': typeof EnviosRoute
  '/favoritos': typeof FavoritosRoute
  '/personalizar-ramo': typeof PersonalizarRamoRoute
  '/rosas-eternas': typeof RosasEternasRoute
  '/sobre-nosotros': typeof SobreNosotrosRoute
  '/mi-cuenta': typeof AuthenticatedMiCuentaRoute
  '/debug/ghl-test': typeof DebugGhlTestRoute
  '/legal/$slug': typeof LegalSlugRoute
  '/producto/$id': typeof ProductoIdRoute
  '/servicios/$slug': typeof ServiciosSlugRoute
  '/servicios': typeof ServiciosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/carrito': typeof CarritoRoute
  '/catalogo': typeof CatalogoRoute
  '/contacto': typeof ContactoRoute
  '/envios': typeof EnviosRoute
  '/favoritos': typeof FavoritosRoute
  '/personalizar-ramo': typeof PersonalizarRamoRoute
  '/rosas-eternas': typeof RosasEternasRoute
  '/servicios': typeof ServiciosRouteWithChildren
  '/sobre-nosotros': typeof SobreNosotrosRoute
  '/_authenticated/mi-cuenta': typeof AuthenticatedMiCuentaRoute
  '/debug/ghl-test': typeof DebugGhlTestRoute
  '/legal/$slug': typeof LegalSlugRoute
  '/producto/$id': typeof ProductoIdRoute
  '/servicios/$slug': typeof ServiciosSlugRoute
  '/servicios/': typeof ServiciosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/carrito'
    | '/catalogo'
    | '/contacto'
    | '/envios'
    | '/favoritos'
    | '/personalizar-ramo'
    | '/rosas-eternas'
    | '/servicios'
    | '/sobre-nosotros'
    | '/mi-cuenta'
    | '/debug/ghl-test'
    | '/legal/$slug'
    | '/producto/$id'
    | '/servicios/$slug'
    | '/servicios/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/carrito'
    | '/catalogo'
    | '/contacto'
    | '/envios'
    | '/favoritos'
    | '/personalizar-ramo'
    | '/rosas-eternas'
    | '/sobre-nosotros'
    | '/mi-cuenta'
    | '/debug/ghl-test'
    | '/legal/$slug'
    | '/producto/$id'
    | '/servicios/$slug'
    | '/servicios'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/carrito'
    | '/catalogo'
    | '/contacto'
    | '/envios'
    | '/favoritos'
    | '/personalizar-ramo'
    | '/rosas-eternas'
    | '/servicios'
    | '/sobre-nosotros'
    | '/_authenticated/mi-cuenta'
    | '/debug/ghl-test'
    | '/legal/$slug'
    | '/producto/$id'
    | '/servicios/$slug'
    | '/servicios/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CarritoRoute: typeof CarritoRoute
  CatalogoRoute: typeof CatalogoRoute
  ContactoRoute: typeof ContactoRoute
  EnviosRoute: typeof EnviosRoute
  FavoritosRoute: typeof FavoritosRoute
  PersonalizarRamoRoute: typeof PersonalizarRamoRoute
  RosasEternasRoute: typeof RosasEternasRoute
  ServiciosRoute: typeof ServiciosRouteWithChildren
  SobreNosotrosRoute: typeof SobreNosotrosRoute
  DebugGhlTestRoute: typeof DebugGhlTestRoute
  LegalSlugRoute: typeof LegalSlugRoute
  ProductoIdRoute: typeof ProductoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carrito': {
      id: '/carrito'
      path: '/carrito'
      fullPath: '/carrito'
      preLoaderRoute: typeof CarritoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogo': {
      id: '/catalogo'
      path: '/catalogo'
      fullPath: '/catalogo'
      preLoaderRoute: typeof CatalogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/envios': {
      id: '/envios'
      path: '/envios'
      fullPath: '/envios'
      preLoaderRoute: typeof EnviosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favoritos': {
      id: '/favoritos'
      path: '/favoritos'
      fullPath: '/favoritos'
      preLoaderRoute: typeof FavoritosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personalizar-ramo': {
      id: '/personalizar-ramo'
      path: '/personalizar-ramo'
      fullPath: '/personalizar-ramo'
      preLoaderRoute: typeof PersonalizarRamoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rosas-eternas': {
      id: '/rosas-eternas'
      path: '/rosas-eternas'
      fullPath: '/rosas-eternas'
      preLoaderRoute: typeof RosasEternasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicios': {
      id: '/servicios'
      path: '/servicios'
      fullPath: '/servicios'
      preLoaderRoute: typeof ServiciosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre-nosotros': {
      id: '/sobre-nosotros'
      path: '/sobre-nosotros'
      fullPath: '/sobre-nosotros'
      preLoaderRoute: typeof SobreNosotrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/mi-cuenta': {
      id: '/_authenticated/mi-cuenta'
      path: '/mi-cuenta'
      fullPath: '/mi-cuenta'
      preLoaderRoute: typeof AuthenticatedMiCuentaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/debug/ghl-test': {
      id: '/debug/ghl-test'
      path: '/debug/ghl-test'
      fullPath: '/debug/ghl-test'
      preLoaderRoute: typeof DebugGhlTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/$slug': {
      id: '/legal/$slug'
      path: '/legal/$slug'
      fullPath: '/legal/$slug'
      preLoaderRoute: typeof LegalSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/producto/$id': {
      id: '/producto/$id'
      path: '/producto/$id'
      fullPath: '/producto/$id'
      preLoaderRoute: typeof ProductoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicios/': {
      id: '/servicios/'
      path: '/'
      fullPath: '/servicios/'
      preLoaderRoute: typeof ServiciosIndexRouteImport
      parentRoute: typeof ServiciosRoute
    }
    '/servicios/$slug': {
      id: '/servicios/$slug'
      path: '/$slug'
      fullPath: '/servicios/$slug'
      preLoaderRoute: typeof ServiciosSlugRouteImport
      parentRoute: typeof ServiciosRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedMiCuentaRoute: typeof AuthenticatedMiCuentaRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedMiCuentaRoute: AuthenticatedMiCuentaRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ServiciosRouteChildren {
  ServiciosSlugRoute: typeof ServiciosSlugRoute
  ServiciosIndexRoute: typeof ServiciosIndexRoute
}

const ServiciosRouteChildren: ServiciosRouteChildren = {
  ServiciosSlugRoute: ServiciosSlugRoute,
  ServiciosIndexRoute: ServiciosIndexRoute,
}

const ServiciosRouteWithChildren = ServiciosRoute._addFileChildren(
  ServiciosRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CarritoRoute: CarritoRoute,
  CatalogoRoute: CatalogoRoute,
  ContactoRoute: ContactoRoute,
  EnviosRoute: EnviosRoute,
  FavoritosRoute: FavoritosRoute,
  PersonalizarRamoRoute: PersonalizarRamoRoute,
  RosasEternasRoute: RosasEternasRoute,
  ServiciosRoute: ServiciosRouteWithChildren,
  SobreNosotrosRoute: SobreNosotrosRoute,
  DebugGhlTestRoute: DebugGhlTestRoute,
  LegalSlugRoute: LegalSlugRoute,
  ProductoIdRoute: ProductoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
